### ISSUE TITLE
Fix bug where opening JSON file breaks things

### ISSUE THREAD

**Issue by bee-san** [bee-san/pyWhat#116]
```
C:\Users\xxx>ciphey -t "aGVsbG8gbXkgbmFtZSBpcyBiZWU="
Traceback (most recent call last):
File "d:\python\python37\lib\runpy.py", line 193, in _run_module_as_main
"main", mod_spec)
File "d:\python\python37\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "D:\Python\Python37\Scripts\ciphey.exe_main.py", line 7, in
File "d:\python\python37\lib\site-packages\click\core.py", line 829, in call
return self.main(*args, **kwargs)
File "d:\python\python37\lib\site-packages\click\core.py", line 782, in main
rv = self.invoke(ctx)
File "d:\python\python37\lib\site-packages\click\core.py", line 1066, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "d:\python\python37\lib\site-packages\click\core.py", line 610, in invoke
return callback(*args, **kwargs)
File "d:\python\python37\lib\site-packages\ciphey\ciphey.py", line 222, in main
config.complete_config()
File "d:\python\python37\lib\site-packages\ciphey\iface_config.py", line 189, in complete_config
self.load_objs()
File "d:\python\python37\lib\site-packages\ciphey\iface_config.py", line 132, in load_objs
_fwd.registry.get_named(self.checker, PolymorphicChecker)
File "d:\python\python37\lib\site-packages\ciphey\iface_config.py", line 102, in call
return self.instantiate(t)
File "d:\python\python37\lib\site-packages\ciphey\iface_config.py", line 97, in instantiate
ret = t(self)
File "d:\python\python37\lib\site-packages\ciphey\iface_modules.py", line 153, in init
self._base = cls(config)
File "d:\python\python37\lib\site-packages\ciphey\basemods\Checkers\ezcheck.py", line 46, in init
self.checkers.append(config(What))
File "d:\python\python37\lib\site-packages\ciphey\iface_config.py", line 102, in call
return self.instantiate(t)
File "d:\python\python37\lib\site-packages\ciphey\iface_config.py", line 97, in instantiate
ret = t(self)
File "d:\python\python37\lib\site-packages\ciphey\iface_modules.py", line 153, in init
self.base = cls(config)
File "d:\python\python37\lib\site-packages\ciphey\basemods\Checkers\what.py", line 59, in init
self.id = identifier.Identifier()
File "d:\python\python37\lib\site-packages\pywhat\identifier.py", line 10, in init
self.regex_id = RegexIdentifier()
File "d:\python\python37\lib\site-packages\pywhat\regex_identifier.py", line 11, in init
self.regexes = json.load(myfile)
File "d:\python\python37\lib\json_init.py", line 293, in load
return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence
```

**Comment by cnseu** [comment]
hi! Did you solve this problem? i meet this error either in the win10-64bit platform.

**Comment by piatrashkakanstantinass** [comment]
> hi! Did you solve this problem? i meet this error either in the win10-64bit platform.

What is your system language?

**Comment by piatrashkakanstantinass** [comment]
I guess, [this](https://github.com/rkern/line_profiler/issues/37) may work.
